replicaCount: 2

image:
  repository: infinityapi
  tag: latest
  pullPolicy: IfNotPresent

postgresImage:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

postgresService:
  type: ClusterIP
  port: 5432

postgres:
  dbName: infinityapi
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi

secrets:
  dbUser: infinity
  dbPassword: infinity

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
