version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: infinityapi_postgres
    environment:
      POSTGRES_DB: infinityapi
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
    volumes:
      - /home/ubuntu/postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  infinityapi:
    image: infinityapi:latest
    container_name: infinityapi
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: xxxx
      DB_PASSWORD: xxxx
      DB_NAME: infinityapi
      HTTP_LISTENER: 0.0.0.0
      HTTP_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    command: ["/app/infinityapi", "-startserver"]

