apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infinityapi-chart.fullname" . }}-config
  labels:
    {{- include "infinityapi-chart.labels" . | nindent 4 }}
data:
  config.ini: |
    [db]
    host = {{ .Values.secrets.dbHost }}
    port = {{ .Values.secrets.dbPort }}
    user = {{ .Values.secrets.dbUser }}
    password = {{ .Values.secrets.dbPassword }}
    dbname = {{ .Values.postgres.dbName }}
    sslmode = disable

    [server]
    http_listener = 0.0.0.0
    http_port = 8000
