apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infinityapi-chart.fullname" . }}
  labels:
    {{- include "infinityapi-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "infinityapi-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "infinityapi-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ include "infinityapi-chart.fullname" . }}-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "infinityapi-chart.fullname" . }}-db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "infinityapi-chart.fullname" . }}-db-secret
                  key: db-password
            - name: DB_NAME
              value: {{ .Values.postgres.dbName }}
            - name: HTTP_LISTENER
              value: "0.0.0.0"
            - name: HTTP_PORT
              value: "8000"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
